version: 2

jobs:
    build:
        docker:
            # the Docker image with Cypress dependencies
            - image: cypress/base:12.16.1
              environment:
                  ## this enables colors in the output
                  TERM: xterm
        working_directory: ~/app
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-deps-{{ .Branch }}-{{ checksum "e2e/package-lock.json" }}
                      - v2-deps-{{ .Branch }}-
                      - v2-deps-
            - run: cd e2e && npm ci
            - save_cache:
                  key: v2-deps-{{ .Branch }}-{{ checksum "e2e/package-lock.json" }}
                  paths:
                      - ~/.npm
                      - ~/.cache
            - run:
                  name: Install jq
                  command: cd e2e && apt-get update && apt-get install -y jq
            - run:
                  name: Running E2E tests with recording
                  when: on_success
                  command: cd e2e && npm run test:cypress:record
            - run:
                  name: Combine MochaAwesome Reports
                  when: always
                  command: cd e2e && make combine-reports && make generate-report
            - store_test_results:
                  path: e2e/cypress/reports
            - store_artifacts:
                  path: e2e/mochareports
            - store_artifacts:
                  path: e2e/cypress/videos
            - store_artifacts:
                  path: e2e/cypress/screenshots
            #   - run:
            #       name: Publish test artefacts s3 bucket
            #       when: always
            #       command: cd e2e && make publish-reports-s3
            - run:
                  name: Slack Custom Reporting
                  when: always
                  command: cd e2e && make slack-alert
