version: '2.2'
services:
    cypresstestdocker:
        image: cypresstestdocker
        environment:
            - URI_ROOT=the-internet.herokuapp.com
        stdin_open: true
        tty: true
        volumes:
            - ./:/app
            - node_modules:/app/node_modules
            
volumes:
  node_modules: